project:
  type: book

book:
  title: "1"
  author: "Norah Jones"
  date: "2026/4/2"
  chapters:
    - index.qmd
    - intro.qmd
    - pic.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



